name: LZA Lint
on:
  workflow_call:
    inputs:
      lint_target:
        type: string
        required: false
        default: "lint"
      aws_role_arn:
        type: string
        required: true
      aws_region:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  lza-lint:
    name: LZA Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_role_arn }}
          aws-region: ${{ inputs.aws_region }}

      - name: Docker build
        run: docker-compose build aws-cli

      - name: Lint LZA configuration files
        id: lint
        shell: bash
        run: make ${{ inputs.lint_target }}

