name: validate env variables

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  validate-environment:
    name: validate-environmental-vars
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: |
          echo "Validating input ${{ inputs.environment }}"
      - name: validate required environment
        if: inputs.environment == '' 
        run: |
          echo "Defined environment seems to be empty. Please check if the defined environment variable exists"
          exit 1
  validate-env:
    name: validate-required-fields
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.environment) }}
    environment: ${{ matrix.deploy_env }}
    steps:
      - name: validate required fields
        env:
          BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
          DPLATFORM: ${{ vars.DPLATFORM }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
        run: |
          declare -i EXIT=0
          [ -z $BASE_DOMAIN ] && echo "'BASE_DOMAIN' env var is not present in environment '$ENVIRONMENT'" && EXIT=1
          [ -z $PROJECT_ID ] && echo "'PROJECT_ID' env var is not present in environment '$ENVIRONMENT'" && EXIT=1
          [ -z $DPLATFORM ] && echo "'DPLATFORM' env var is not present in environment '$ENVIRONMENT'" && EXIT=1
          [ -z $PROJECT_NUMBER ] && echo "'PROJECT_NUMBER' env var is not present in environment '$ENVIRONMENT'" && EXIT=1
          exit $EXIT



